names =['sahar','ahkam','alaa','seham','asmaa']
print(f" hi {names[0].title()} nice to meet you")
print(f" hi {names[1].title()} nice to meet you")
print(f" hi {names[2].title()} nice to meet you")
print(f" hi {names[3].title()} nice to meet you")
print(f" hi {names[4].title()} nice to meet you")
print('#'*30)
print(f" hi {names[-5].title()} nice to meet you")
print(f" hi {names[-4].title()} nice to meet you")
print(f" hi {names[-3].title()} nice to meet you")
print(f" hi {names[-2].title()} nice to meet you")
print(f" hi {names[-1].title()} nice to meet you")
print('#'*30)
print(f" hi {names[-1].title()} nice to meet you")
print(f" hi {names[-2].title()} nice to meet you")
print(f" hi {names[-3].title()} nice to meet you")
print(f" hi {names[-4].title()} nice to meet you")
print(f" hi {names[-5].title()} nice to meet you")