names =['sahar','ahkam','alaa','seham','asmaa']
print(names[0].title())
print(names[1].title())
print(names[2].title())
print(names[3].title())
print(names[4].title())
print('#'*30)
print(names[-5].title())
print(names[-4].title())
print(names[-3].title())
print(names[-2].title())
print(names[-1].title())
print('#'*30)
print(names[-1].title())
print(names[-2].title())
print(names[-3].title())
print(names[-4].title())
print(names[-5].title())