cars =['kia','IBM','sunny','motorela']
print(f'I would like to own a {cars[0].title()} car.')
print(f'I would like to own a {cars[1].title()} car.')
print(f'I would like to own a {cars[2].title()} car.')
print(f'I would like to own a {cars[3].title()} car.')
print('-'*50)
print(f'I would like to own a {cars[-1].upper()} car.')
print(f'I would like to own a {cars[-2].upper()} car.')
print(f'I would like to own a {cars[-3].upper()} car.')
print(f'I would like to own a {cars[-4].upper()} car.')
print('-'*50)
print(f'I would like to own a {cars[-4].lower()} car.')
print(f'I would like to own a {cars[-3].lower()} car.')
print(f'I would like to own a {cars[-2].lower()} car.')
print(f'I would like to own a {cars[-1].lower()} car.')